name: integration test and linting

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: action/setup-node@v4

      - name: checkout source code
        uses: action/checkout@v4

      - name: install dependencies
        run: npm i

      - name: check linting
        run: npm run lint

      - name: run test
        run: npm test
